### ISSUE TITLE
Git ignore fix

### ISSUE THREAD

**Issue by Glu3e** [NikitaChernykh/Portfolio#1]
try just putting:  `node_modules` in your git ignore file. when i opened yours there was a bunch of stuff there.

**Comment by NikitaChernykh** [comment]
@Glu3e I now ignore node_modules in my few last commits I managed to do it correctly

**Comment by NikitaChernykh** [comment]
@Glu3e the problem was that I pushed my first commit together with node_modules and without gitignore. To ingnore it correctly I should have pushed it with gitignore from beginning. So to undo what i did the only way is to remove node_modules from the repo but I still have them on my local so next time I push a commit my gitignore will ignore it correctly.

**Comment by Glu3e** [comment]
@NikitaChernykh  i see!
